### ISSUE TITLE
Use project link to point to https://sybil.readthedocs.io/en/latest/ ?

### ISSUE THREAD

**Issue by hartwork** [cjw296/sybil#11]
Hi!

it would be cool to have a quick way to go to https://sybil.readthedocs.io/en/latest/ from here. The project link is still unfilled and might make a great place for it.

Best, Sebastian

**Comment by cjw296** [comment]
Done! You can also click on the [![Documentation Status](https://readthedocs.org/projects/sybil/badge/?version=latest)](https://sybil.readthedocs.io/en/latest/?badge=latest) badge :-)

**Comment by hartwork** [comment]
Nice!
