### ISSUE TITLE
Recursive globs in pattern argument

### ISSUE THREAD

**Issue by pauleveritt** [cjw296/sybil#13]
I have `.rst` files I'd like tested, but they in child directories under the root. I'd like a pattern of something like '**/*.rst' using the improved glob support in Python post-3.5

If that's not feasible, can path optional be a sequence of places to look?

**Comment by cjw296** [comment]
Can you show me the code you currently have to pick up your .rst files?
What would need to change? A PR for this would be great!

**Comment by pauleveritt** [comment]
I worked around it by writing a separate `test_**.py` file for each child directory in the docs. I'll see about doing a PR.
