### ISSUE TITLE
CodeBlockParser: Automatically skip non-Python snippets

### ISSUE THREAD

**Issue by Gallaecio** [cjw296/sybil#17]
I am getting syntax errors from a Bash code block (`.. code-block:: bash`). Could sybil automatically ignore non-Python snippets?

**Comment by cjw296** [comment]
Sybil doesn't do anything with `code-block:: bash` unless you've supplied a custom parser.
What's the full traceback and exception you're seeing?

**Comment by Gallaecio** [comment]
I believe my issue with Bash [also stemmed from a mixup of Sybil and doctest](https://github.com/cjw296/sybil/issues/16#issuecomment-552760152). When I run tests against a specific `.rst` file, it seems pytest runs doctest even if it’s not enabled, but everything works if I run the tests for the containing folder instead.

**Comment by cjw296** [comment]
Oh yes, now that you mention it, I remember this and it's a pretty frustating bug in pytest:
https://github.com/pytest-dev/pytest/issues/4954#issuecomment-478053157
Please follow up there in the hope it might get some priority :-)
