### ISSUE TITLE
provide the integration as pytest plugin instance instead of generating a function with a hidden instance

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [cjw296/sybil#2]
the idiomatic way to configure pytest for sybil is to add a plugin to pytest

then a conftest would read:
```python
import pytest
from sybil import Sybil
from sybil.parsers.codeblock import CodeBlockParser
from sybil.parsers.doctest import DocTestParser

pytest_plugins = "sybil.integration.pytest

@pytest.fixture()
def sybil_dir(tmpdir, monkeypatch):
    # there are better ways to do temp directories, but it's a simple example:
    path = tmpdir.mkdir('sybil')
    monkeypatch.chdir(path)
    return path

def pytest_sybil_configure():
  return Sybil(
     parsers=[
        DocTestParser(),
        CodeBlockParser(future_imports=['print_function']),
      ],
      pattern='*.rst',
      fixtures=['sybil_dir']
    )
```

**Comment by cjw296** [comment]
Not sure what "pytes" means? Typo?

Using the `pytest_sybil_configure` hook, how and where would a sequence of `SybilFile` instances be returned?

**Comment by RonnyPfannschmidt** [comment]
the collection and SybilFile item generation would happen inside of the pytest integration inside sybil

**Comment by cjw296** [comment]
Okay, but what would that look like? Could you hack up a quick PR to demonstrate?

Also, what would be the advantages of implementing the integration in the way you describe, versus the current way?

**Comment by RonnyPfannschmidt** [comment]
one of the advantages would be that sybil eventually could support a oppiniated default configuration

**Comment by cjw296** [comment]
Hmm, explicit is better than implicit, no? I've found this config differs a lot between projects, so not sure that should be a goal ;-)

(for example: PyTest is unlikely to use the same collection of parsers as testfixtures...)

**Comment by RonnyPfannschmidt** [comment]
true

**Comment by cjw296** [comment]
This is also a pattern I liked in [Manuel](http://pythonhosted.org/manuel/index.html#using-unittest). 
With that in mind, is there a good reason for the change, or can I close this issue?

**Comment by RonnyPfannschmidt** [comment]
@cjw296 the creation of a opinionated default is a bit unrelated nicely fitting the plugin ecosystem so i'd like to leave this open, o hope i can return to providing the pr i promised this week

**Comment by cjw296** [comment]
No rush, I'll likely need to support the current integration going forward. I'm still looking for the compelling reason for the change ;-) Sybil doesn't seek to be a plugin for any particular test runner (it has to for Nose, there was no other way), so unless there's a strong reason that it *needs* to be a plugin, I'd prefer to keep the integration as is.

**Comment by RonnyPfannschmidt** [comment]
its mainly about providing the plugin bits it provides for pytest in a more idiomatic way

**Comment by cjw296** [comment]
Keen to see what it looks like, but can't promise to merge it unless there's a compelling reason. Pytest has many idioms, some of them are even documented ;-) `pytest_collect_file` seems like the obvious entry point for Sybil, I'm fairly sure you may even have recommended it to me...

**Comment by RonnyPfannschmidt** [comment]
@cjw296 i recall recommending it for a conftest ^^

**Comment by cjw296** [comment]
sure, that's where the Sybil integration is used :-)

**Comment by cjw296** [comment]
Okay, will await the PR but closing this in the meantime.
