### ISSUE TITLE
UTF-8 documents don't work in Windows

### ISSUE THREAD

**Issue by kmike** [cjw296/sybil#20]
Hey! See https://scrapinghub.visualstudio.com/scrapy/_build/results?buildId=5&view=logs&j=19c563d8-3dcd-57d1-cd5e-9dd946b0a29b&t=4292cd33-74e4-56d2-4fed-99bb1e6ffbb8&l=117:

https://github.com/cjw296/sybil/blob/63f4d8251f9c8156a36b02da7609d841b3c3faff/sybil/document.py#L39 opens file without specifying an encoding; it means encoding is system-dependent. I think this is the problem which caused the test failure above: your file with a doctest has some specific encoding (e.g. utf-8), it doesn't vary based on machine.

I'm not sure how to fix that properly, but opening with utf8 encoding always could work.

**Comment by cjw296** [comment]
What encoding is `tutorial.rst ` in?
What is your default system encoding?
What happens if you specify `PYTHONIOENCODING=utf8` as an environment variable in your windows shell environment?

**Comment by kmike** [comment]
FIle is in utf-8. Default system encoding seems to be windows-1252. I think PYTHONIOENCODING would fix it, but it doesn't seem right, because this way global behavior is modified, and potentially some other parts of the code may rely on a previous, default behavior.

**Comment by cjw296** [comment]
How would you like to express in your sybil config that your text files are in utf-8?
In your case, it does appear all your files are in utf-8, so I suspect the environment variable approach is actually what you want.

**Comment by kmike** [comment]
I think there are several related questions, which are not the same though.

1. Should sybil use system default encoding to open file? I think no, because encoding of the documentation files doesn't depend on a system tests are running on. There is always a single correct encoding for these files - the one which the project selected to use.
2. What should be the default encoding to open a file? I think UTF-8 is a good default; it is a default in Sphinx, and was the only supported encoding in past (see https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_encoding). 
3. If a default encoding is not correct, how to override it? I don't have a strong preference here, but I think it should be some sybil-specific configuration, not a global switch like PYTHONIOENCODING env variable, which changes the behavior of all code.

**Comment by cjw296** [comment]
I believe the 1.3.0 release addresses all of your points :-)

**Comment by kmike** [comment]
Awesome, thanks @cjw296 for fixing it so quickly!
