### ISSUE TITLE
How can I control the module that classes and functions are created in?

### ISSUE THREAD

**Issue by warsaw** [cjw296/sybil#21]
I'm am working on modernizing my [public](https://gitlab.com/warsaw/public) library, which involves switching over to pytest.  I've already made this switch on other libraries, and Sybil has been fantastic for integrating my `.rst` file based doctests.  Great work @cjw296 !

However, with `public`, functions and classes in my `using.rst` file need to be defined in a module that ends up in `sys.modules` and have `__module__` attributes.  This doesn't seem to be the case by default.  What's especially weird is that functions `__module__` attribute are `None`, while class `__module__` attributes are `builtins`.  I don't know if that's intentional or just a strange unexpected behavior.

I can't quite work out how to ensure that classes and functions in my `using.rst` file get created and attached within a `sys.modules` present module.  Any clues/help would be greatly appreciated!

**Comment by cjw296** [comment]
Thanks! I had a quick scan through your repo but couldn't find where you were wiring Sybil in.
What parsers are you using? Specifically, for the ones for `using.rst`, which I'm afraid I couldn't find in the repo either...

**Comment by warsaw** [comment]
Ah, sorry I'd forgotten to push [this branch](https://gitlab.com/warsaw/public/-/tree/modernize).  Here's my [conftest.py](https://gitlab.com/warsaw/public/-/blob/modernize/conftest.py) file which is where I set up Sybil integration.

**Comment by warsaw** [comment]
I got a little farther by creating a module object and putting it's name in the namespace passed to the `setup`.  But it's still not pulling the `__all__` from the right place.

**Comment by cjw296** [comment]
Are the problematic objects being created in a doctest executor or in a `.. code-block:: python` executor?

**Comment by warsaw** [comment]
doctest executor I believe.  they are just `>>>` examples in my `.rst` file.

**Comment by warsaw** [comment]
For example, [this line](https://gitlab.com/warsaw/public/-/blob/modernize/public/docs/using.rst#L82) fails because

```
__________________________ using.rst line=82 column=1 __________________________

Example at /Users/barry/projects/public/public/docs/using.rst, line 82, column 1 did not evaluate as expected:
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest None[0]>", line 1, in <module>
    NameError: name '__all__' is not defined

public/docs/using.rst:82: SybilFailure
_________________________ using.rst line=111 column=1 __________________________
```

**Comment by warsaw** [comment]
But `__all__` is defined in `testmod`, the test module I create and put `__name__` of in the namespace.

**Comment by cjw296** [comment]
If all your examples are `>>>`, you can safely omit the CodeBlockParser from your conftest.py. 
Since it's doctests in play here, this is likely @tim-one's fault  <0.9 wink>.

Just occurred to me that I didn't check to ask: were these examples being tested before? If so, how? We need to try and find out what's different :-)

That line in the middle of the traceback is the key one, that's where doctest is exec'ing the code it's just compiled in the `test.globs` namespace. I don't l know how important it may be that the `exec` there is only passing globals and not locals?

The most salient bit of the sybil codebase is here, but I can't spot any obvious bugs that might cause this:
https://github.com/cjw296/sybil/blob/b54d9e9b57e0579e6ad0b36879ebbaf60d1f1905/sybil/parsers/doctest.py#L115-L125

**Comment by cjw296** [comment]
Another possibility: is the parser finding all the previous blocks? If not, then this could be a [regex](https://nedbatchelder.com/blog/201204/two_problems.html) problem.

**Comment by cjw296** [comment]
In terms of debugging, I guess a pdb at [this line ](https://gitlab.com/warsaw/public/-/blob/modernize/public/public.py#L61)would show us what `__dict__` is being found.

Given [this line](https://gitlab.com/warsaw/public/-/blob/modernize/public/public.py#L55), I wonder if the test setup needs to find a way to get `test_module.__dict__` to be the sybil `namespace`? That's potentially tricky, since a module's `__dict__` is read only. I wonder if getting `sys._getframe(1).f_globals` to be what we want here might be easier?

**Comment by warsaw** [comment]
I've done a bunch of debugging of the `public` code, and I think I've reached the same basic conclusion as you - that there's some wonkiness in the stdlib's doctest code w.r.t. the module and/or namespace it is executing code in.  Setting `__name__` to match a handcrafted test module in the doctest namespace doesn't seem to do the trick.  I really didn't want to have to wade into the doctest code, but that's probably inevitable.

I had the same question as you, but when I run the test suite on `public` master branch, it does *not* run the `using.rst` doctests.  I really thought it had, but since I haven't touched the code in a long time, who knows?  It doesn't run it now; maybe it never did and this weird behavior has been lurking the whole time.

Thanks for your help @cjw296 !  I'll continue to investigate.  I'll also look through Roundups bugs to see if anybody else has come across anything similar.  Stay tuned!

**Comment by warsaw** [comment]
So the trick does appear that the namespace (specifically, I think `test.globs` as its defined in doctest) isn't the same namespace as gets passed to the setup/teardown in Sybil.  I don't know how to fix that, but fortunately it looks like I don't have to.  All I have to do is make sure that `testmod.__all__` and `namespace['__all__']` share the same list object, which is good enough for the doctests.

[This line](https://gitlab.com/warsaw/public/-/blob/modernize/conftest.py#L16) does the trick.  Now `using.rst` passes.

I'm going to go ahead and close the issue because there's isn't anything for Sybil to do, but I really appreciate the help in finding a good workaround.

**Comment by cjw296** [comment]
Hmm, I'm pretty sure the namespace are (well, should be!) the same dictionary throughout the running of each `.rst` file:
- [Creation](https://github.com/cjw296/sybil/blob/master/sybil/document.py#L31)
- [Passed to the evaluator](https://github.com/cjw296/sybil/blob/master/sybil/example.py#L53)
- [Through to the doctest](https://github.com/cjw296/sybil/blob/master/sybil/parsers/doctest.py#L117-L120)
- [Making sure it's the same](https://github.com/cjw296/sybil/blob/master/sybil/parsers/doctest.py#L37) as DocTest normally takes a copy of the namespace.

Sounds like the workaround with `__all__` is pragmatic, though, so glad it's working!

This kind of thing reminds me that I wish Sybil and @nedbat's excellent coverage tool could play nicely together, such that you could be sure that all the examples are being executed! (then we'd know if they were running before :-) )

Anyway, glad Sybil's been of help, please let me know if you find anything missing and I'll see what I can do!
