### ISSUE TITLE
Numerours PytestDeprecationWarning raised when using Sybil

### ISSUE THREAD

**Issue by thirtytwobits** [cjw296/sybil#29]
```
myvenv/python3.9/site-packages/sybil/integration/pytest.py:58: 193 warnings
  myvenv/lib/python3.9/site-packages/sybil/integration/pytest.py:58: PytestDeprecationWarning: A private pytest class or function was used.
    self._request = fixtures.FixtureRequest(self)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

This has been going on for awhile. Doesn't break anything but it does normalize deviance having a huge number of warnings we are supposed to ignore.

Any ideas how we could fix this?

**Comment by cjw296** [comment]
Do you have the full traceback for one of these?

**Comment by jborbely** [comment]
As of pytest [6.2.0](https://docs.pytest.org/en/6.2.x/changelog.html#pytest-6-2-0-2020-12-12) the ``FixtureRequest`` class (and many other classes within ``_pytest``) should be accessed [this](https://docs.pytest.org/en/6.2.x/changelog.html#improvements) way.

However, the docs state

> Constructing them is not supported (except for MonkeyPatch); they are only meant for use in type annotations. Doing so will emit a deprecation warning, and may become a hard-error in pytest 7.0.
>
> Subclassing them is also not supported. This is not currently enforced at runtime, but is detected by type-checkers such as mypy.

**Comment by jborbely** [comment]
@thirtytwobits You can silence this warning from being displayed by adding the following to your [ini](https://docs.pytest.org/en/latest/how-to/capture-warnings.html#deprecationwarning-and-pendingdeprecationwarning) file

```ini
[pytest]
filterwarnings =
    ignore:A private pytest class or function was used:DeprecationWarning
```

**Comment by cjw296** [comment]
Yeah, let's see what the latest hoop is that Sybil needs to jump through: https://github.com/pytest-dev/pytest/issues/8832

**Comment by cjw296** [comment]
Fixed in https://github.com/cjw296/sybil/commit/56daa2f1eb0df34a9fb1b992fbc3d686457b8338

**Comment by thirtytwobits** [comment]
Awesome! Tested this change against my code and it works great. Thanks.
